spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <PLACEHOLDER>
            client-secret: <PLACEHOLDER>
server:
  servlet:
    session:
      persistent: false
